# --*-HogWarts-HDC-*--
# --*-UTF-8-*--
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDemo():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()

    def teardown_method(self, method):
        self.driver.quit()

    def test_one(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.maximize_window()
        # self.driver.set_window_size(929, 692)
        time.sleep(3)
        # self.driver.implicitly_wait(5)
        self.driver.find_element(By.LINK_TEXT, "热门").click()
        time.sleep(3)
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        element = self.driver.find_element(By.LINK_TEXT, "所有分类")
        result = element.get_attribute("class")
        time.sleep(3)
        # 断言
        assert result == "active"
