# --*-HogWarts-HDC-*--
# --*-UTF-8-*--
# Generated by Selenium IDE
import shelve

import pytest
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By


class TestDemo():
    def setup_method(self, method):
        options = Options()
        options.debugger_address = "127.0.0.1:9222"
        self.driver = webdriver.Chrome()

    #   chrome --remote-debugging-port=9222

    def teardown_method(self, method):
        self.driver.quit()

    # def test_one(self):
    #     self.driver.get("https://baidu.com/")
    #     time.sleep(3)

    # def test_two(self):
    #     self.driver.find_element(By.ID, "menu_contacts").click()
    #     time.sleep(3)

    def test_three(self):
        # cookies = self.driver.get_cookies()
        # print(cookies)
        cookies = [
            {'domain': '.qq.com', 'expiry': 1603506481, 'httpOnly': False, 'name': '_gat', 'path': '/', 'secure': False,
             'value': '1'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.vid', 'path': '/', 'secure': False,
             'value': '1688853112947872'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.vst', 'path': '/', 'secure': False,
             'value': 'xn6zfOYc4qbITAI1Ldo8x5VWxxtoXYUs7Evn_Ouc0igzRtseo9ecv90IR0H8oYjSNZVhNjGsxx0DXTj4PS5791EHMY_KEcWG4dKxysF0iuTipHQAAz9HTcZLgYR54HVSbsKpmfxvVyYaw_rkJz89KW6OMondMADlwP_NTgZhHshXh1GiNMDmknDM-XqaDCgAKt2nASPiambAneHtMX0fdMZCPxzhlkS3kBflwcZyktD-txwK63z6I4Ju8SaKDUeulBHxcrLv0frdUR4RfHFeyg'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.vid', 'path': '/', 'secure': False,
             'value': '1688853112947872'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.corpid', 'path': '/', 'secure': False,
             'value': '1970325133172271'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.d2st', 'path': '/', 'secure': False,
             'value': 'a3011435'},
            {'domain': 'work.weixin.qq.com', 'expiry': 1603537868, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/',
             'secure': False, 'value': '8h83k2t'},
            {'domain': '.qq.com', 'expiry': 1603592752, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False,
             'value': 'GA1.2.1973754571.1603506336'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d',
             'path': '/', 'secure': False, 'value': '1603506334'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/', 'secure': False,
             'value': '36474963041534483'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.sid', 'path': '/', 'secure': False,
             'value': 'xY6DNOR1cq4uxH5BiqIEPo5rs9dupyJ_0BrtRZlpNvNBDRITq5U0O-Cg-FN0GV5w'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ltype', 'path': '/', 'secure': False,
             'value': '1'}, {'domain': '.work.weixin.qq.com', 'expiry': 1635042333, 'httpOnly': False,
                             'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': False,
                             'value': '1603462424,1603506334'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': False,
             'value': 'direct'},
            {'domain': '.qq.com', 'expiry': 1666578352, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False,
             'value': 'GA1.2.1091464111.1603506336'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1634998414, 'httpOnly': False, 'name': 'wwrtx.c_gdpr',
             'path': '/', 'secure': False, 'value': '0'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1606098425, 'httpOnly': False, 'name': 'wwrtx.i18n_lan',
             'path': '/', 'secure': False, 'value': 'zh'}]
        # db = shelve.open("cookies")
        # # db["cookie"] = cookies
        # # db.close()
        # cookies = db["cookie"]
        # self.driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx?redirect_uri=https://work.weixin.qq.com/wework_admin/frame#index")
        # time.sleep(3)
        # for cookie in cookies:
        #     self.driver.add_cookie(cookie)
        # self.driver.refresh()
        # time.sleep(3)
        # self.driver.find_element(By.XPATH, '//*[@class="index_service_cnt js_service_list"]/a[2]').click()
        # time.sleep(3)

        # self.driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx?redirect_uri=https://work.weixin.qq.com/wework_admin/frame#index")
        # for cookie in cookies:
        #     self.driver.add_cookie(cookie)
        #
        # self.driver.refresh()
        # # self.driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx?redirect_uri=https://work.weixin.qq.com/wework_admin/frame#index")
        # time.sleep(3)

        self.driver.get(
            "https://work.weixin.qq.com/wework_admin/loginpage_wx?redirect_uri=https://work.weixin.qq.com/wework_admin/frame#index")
        time.sleep(5)
        for cookie in cookies:
            self.driver.add_cookie(cookie)
        self.driver.refresh()
        time.sleep(5)
        self.driver.find_element(By.XPATH, '//*[@class="index_service_cnt js_service_list"]/a[2]').click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, '//*[@class="ww_fileImporter_fileContainer_uploadInputMask"]').send_keys(
            "D:/tongxunlu.xlsx")
        time.sleep(5)
        filename = self.driver.find_element(By.CSS_SELECTOR, ".ww_fileImporter_fileContainer_fileNames").text
        print(filename)
        assert filename == "tongxunlu.xlsx"
        time.sleep(5)
